---
title: "Introduction"
---


### Evaluating MLL with harvest occurring below MLL

Output controls like bag and length limits are a common tool used to 
prevent overfishing and manage size structure of inland freshwater fish 
populations. 
* Meet varying objectives
    * Harvest opportunities: subsistence, deep hooking, so on
    * Simplicity
    * Size structure - minimize harvest of big fish
* Reduced bag limits (25 to 10) increased mean size of panfish on 
average 20.3 mm {Rypel, 2015 #5166} 
* a 200-mm minimum length limit did minimally increase size structure at 
current levels of exploitation across all 18 bluegill populations, the 
populations with the lowest natural mortality and fastest growth 
provided the highest increase in size structure with the lowest 
reduction in yield and number harvested {Paukert, 2002 #5167} 
* MLL have limited effect in catch and release fishery - Miranda et al 
in review 
* YPR results suggest a length limit could improve both yield and 
average weight for crappie fisheries only if growth is rapid and natural 
mortality is low {Allen, 1995 #4836} 


    

### Crappie Management using length limits [keep?]

Due to increased fishing pressure and angler success minimum length limits (MLL) have become a necessary
 management tool to prevent overharvest and to meet angler demands for larger fish in the system
 (Boxrucker 2002; Hale et al. 1999).
* The use of harvest restrictions can help improve harvest only if growth is fast and natural mortality
 is low.
* Conversely, crappie population yield will potentially decrease when growth is slower and natural
 mortality increases (Miranda and Allen 1995). 
* Black crappie _Pomoxis nigromaculatus_ and white crappie _Pomoxis annularis_ are popular and 
 economically important North American sport fish.
* Many anglers often cite crappie as first or second in angler preference (McDonough and Buchanan 1991;
 Mitzner 1991).
* Deep hooking, subsistence, harvest opportunity


### Lake Washington and declines, not data evidence, but needed YPR

* Lake Washington is well known for the number of crappie caught, as well as, producing trophy sized fish.
* It is a very popular crappie fishery for recreational, tournament, as well as subsistence anglers. 
* Since many local anglers are fishing for subsistence, a unique rule for the system, the “5 under rule”,
 was put in place.
* This rule allows anglers to keep up to 5 fish under the current MLL of 254 mm a day.
* In 2015, a petition was signed by 595 anglers that called for an increase in the Minimum Length Limit (MLL) and to drop the
 “5 under rule”.
* Anglers who signed this petition gave the primary reason for wanting a new regulation was that harvest rates and average
 weights had decreased in recent years with increased fishing pressure.
* MDWFP monitoring data has not shown an obvious decline
* Mississippi Department of Wildlife, Fisheries and Park wanted to evaluate the effects on yield of MLL of 254, 279.4, or
 304.8 millimeter MLL.

 
### Other systems with over under regualtions, not unquie to lake washington

* Florida 2016- Largemouth bass 5 daily, only 1 over 16 inches (http://myfwc.com/fishing/freshwater/black-bass/bass-regulations/changes/)
    * Done to simplify regulations, no zones with different length and bag limits
    * Simplicy among waters
    * it is ok to harvest smaller fish, especially bass
* Bass (Largemouth, smallmouth, spotted in Virginia
    * https://www.dgif.virginia.gov/wp-content/uploads/creel-and-length-limits.pdf
    * Smith Mt. Lake and its tributaries below Niagara Dam, only 2 of 5 less than 14 inches
    * Base of Shenandoah Dam, near Town of Shenandoah, downstream to Luray Dam, near Luray No bass 14 to 20 inches, only 1 per day longer than 20 inches
* Minnesota walleye and sauger
    * http://www.dnr.state.mn.us/fishmn/regs.html?topic=inland&section=seaons_and_limits
    * 	6 combined, not more than one walleye over 20"
* Idaho - RBT
    * https://idfg.idaho.gov/sites/default/files/seasons-rules-fish-2016-2018.pdf
    * Pend Oreille Lake - RBT limit is 2 only 1 over 20 inches

    
### How to provide an assessment?

* We were unable to find any scientific data that suggest what effect this type of rule may have on yields. 
* Traditionally a Beverton-Holt yield per recruit models (YPR) only take into account harvest above the MLL, but for this
 study we modified this traditional YPR model to be able to evaluate additional harvest below the MLL.
YPR does not do this, at least as implement in FAST/FAMS that use the 
* jones approximation with incomplete beta
* Slots, protected slots, MLL
* Some have done catch & release on ypr {Waters, 1986 #5164}
* Cryptic mortality, discard mortality can effect if high {Coggins, 2007 #3494}
* Colvin et al. set up how to easily handle complex equilibrium ypr {Colvin, 2013 #4635}
* Harvest of small fish, retaining older fish, potential for recruit and growth overfishing, how to
 evaluate
* Used an IBM to evaluate consumption and trophy fishery for muskelunge {Faust, 2016 #5165}

 
### Objectives and study overview

 The objectives of this study were to 
 1. develop a yield per recruit model that accounts for harvest occurring below the MLL, and  
 2. use the model to evaluate a 10, 11, and 12 inch MLL on growth and recruit overfishing.  
